#!/usr/bin/env bash

PYTHON_ENV="env_glm53flash-dflash2-sglang-pr-37818"
INFERENCE_PROVIDER="SGLang"
INFERENCE_ENV=""
MODEL_REPO="RadixArk/GLM-5.3-NVFP4"
MODEL_NAME="glm5next"
SERVED_MODEL_NAME="glm"
CONTEXT_LEN_VALUE=1048576
DEFAULT_TENSOR_PARALLEL_SIZE=8
TRUST_REMOTE_CODE=""
REASONING_PARSER="--reasoning-parser glm45"
ENABLE_AUTO_TOOL_CHOICE=""
TOOL_CALL_PARSER="--tool-call-parser glm47"
GPU_MEM_UTIL_VALUE=0.80
METRICS_FLAG="--enable-metrics"
HOST="0.0.0.0"
DEFAULT_PORT=8000
API_KEY="--api-key YOUR_API_KEY"

BACKEND_MOE_RUNNER_SM90="marlin"
BACKEND_MOE_RUNNER_SM100=""
BACKEND_MOE_RUNNER_SM103=""
BACKEND_MOE_RUNNER_SM120=""
BACKEND_MOE_RUNNER_SM121=""

ENABLE_CACHE_FLAG=0
ENABLE_SPECULATIVE=0
ENABLE_REASONING_PARSER=0
SPECULATIVE=""
QUANTIZATION=""
NO_PREFIX_CACHE=""
REASONING_PARSER_PLUGIN=""
EXTRA_ARGS="--moe-runner-backend marlin"

RECIPE_DIR="/workspace/scripts/recipes"
# shellcheck source=/workspace/scripts/recipes/helpers/inference_recipe.sh
source "$RECIPE_DIR/helpers/inference_recipe.sh"
run_inference_recipe "$@"
