#!/usr/bin/env bash

PYTHON_ENV="env_primeintellect-sglang"
INFERENCE_PROVIDER="SGLang"
INFERENCE_ENV=""
MODEL_REPO="PrimeIntellect/INTELLECT-1-Instruct"
MODEL_NAME="intellect"
SERVED_MODEL_NAME="intellect"
CONTEXT_LEN_VALUE=8192
DEFAULT_TENSOR_PARALLEL_SIZE=1
TRUST_REMOTE_CODE=""
REASONING_PARSER=""
ENABLE_AUTO_TOOL_CHOICE=""
TOOL_CALL_PARSER=""
GPU_MEM_UTIL_VALUE=0.869518
METRICS_FLAG="--enable-metrics"
HOST="0.0.0.0"
DEFAULT_PORT=8000
API_KEY="--api-key YOUR_API_KEY"

BACKEND_MOE_RUNNER_SM90=""
BACKEND_MOE_RUNNER_SM100=""
BACKEND_MOE_RUNNER_SM103=""
BACKEND_MOE_RUNNER_SM120=""
BACKEND_MOE_RUNNER_SM121=""

ENABLE_CACHE_FLAG=0
ENABLE_SPECULATIVE=0
ENABLE_REASONING_PARSER=0
SPECULATIVE=""
QUANTIZATION=""
NO_PREFIX_CACHE="--disable-radix-cache"
REASONING_PARSER_PLUGIN=""
EXTRA_ARGS=""

RECIPE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
source "$RECIPE_DIR/../../tools/recipes/inference_recipe.sh"
run_inference_recipe "$@"
